/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author MathF
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        iMenuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        iMenuCadastro = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        iMenuRelatorio = new javax.swing.JMenuItem();
        menuRelatorio1 = new javax.swing.JMenu();
        iMenuRelatorio1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(190, 26, 43));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ERP para ONG de Materias Reciclavéis");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 800, 60));

        menuArquivo.setText("Geral");

        iMenuSair.setText("Sair");
        iMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(iMenuSair);

        jMenuBar1.add(menuArquivo);

        menuCadastro.setText("Produto");

        iMenuCadastro.setText("Menu");
        iMenuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuCadastroActionPerformed(evt);
            }
        });
        menuCadastro.add(iMenuCadastro);

        jMenuBar1.add(menuCadastro);

        menuRelatorio.setText("Usuário");

        iMenuRelatorio.setText("Menu");
        iMenuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuRelatorioActionPerformed(evt);
            }
        });
        menuRelatorio.add(iMenuRelatorio);

        jMenuBar1.add(menuRelatorio);

        menuRelatorio1.setText("Operacoes");

        iMenuRelatorio1.setText("Menu");
        iMenuRelatorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuRelatorio1ActionPerformed(evt);
            }
        });
        menuRelatorio1.add(iMenuRelatorio1);

        jMenuBar1.add(menuRelatorio1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iMenuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuCadastroActionPerformed
        InterfaceProdutos produtoInterface = new InterfaceProdutos();
        produtoInterface.setVisible(true);
    }//GEN-LAST:event_iMenuCadastroActionPerformed

    private void iMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_iMenuSairActionPerformed

    private void iMenuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuRelatorioActionPerformed
        InterfaceUsuarios usuarioInterface = new InterfaceUsuarios();
        usuarioInterface.setVisible(true);
    }//GEN-LAST:event_iMenuRelatorioActionPerformed

    private void iMenuRelatorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuRelatorio1ActionPerformed
        InterfaceOperacao operacaoInterface = new InterfaceOperacao();
        operacaoInterface.setVisible(true);
    }//GEN-LAST:event_iMenuRelatorio1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem iMenuCadastro;
    private javax.swing.JMenuItem iMenuRelatorio;
    private javax.swing.JMenuItem iMenuRelatorio1;
    private javax.swing.JMenuItem iMenuSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenu menuRelatorio1;
    // End of variables declaration//GEN-END:variables
}
